Fixed missing includes as well as fixes to windows
-Fixed a feature not yet supported in vs2012:
Error: "only static const integral data members can be initialized
within a class"
- Fixed missing boost includes in CMakeLists
- Fixed missing boost #ifdef's for WIN32
- Fixed min/max issue in windows